require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
# use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'DragonDappRN' do

  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  # when not using frameworks  we can remove this line (2/4):
  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
  target 'DragonDappRNTests' do
    inherit! :complete

  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
